sudo: required

services:
  - docker

language: node_js
node_js:
  - 12.16

dist: trusty

cache:
  npm

branches:
  only:
    - master

env:
  global:
    - DOCKER_IMAGE=mag20/app-gui
    - DOCKER_TAG=$TRAVIS_JOB_NUMBER

jobs:
  include:
    - stage: docker build
      before_script:
          - npm install -g @angular/cli
      script:
        - ng lint
        - npm run build
        - docker build -t "$DOCKER_IMAGE":latest .
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag "$DOCKER_IMAGE":latest "$DOCKER_IMAGE":"$DOCKER_TAG"
        - docker push "$DOCKER_IMAGE":latest
        - docker push "$DOCKER_IMAGE":"$DOCKER_TAG"
        - echo "$DOCKER_IMAGE":"$DOCKER_TAG"
        - echo "$DOCKER_IMAGE":latest
